---
- name: Install and Configure Keepalived
  hosts: your_servers
  become: true

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Install Keepalived
      package:
        name: keepalived
        state: present

    - name: Copy Keepalived configuration
      template:
        src: "keepalived_{{ keepalived_state | lower }}.conf.j2"
        dest: "/etc/keepalived/keepalived.conf"
      notify: restart keepalived
