---
- name: Install and Configure Keepalived
  hosts: all
  become: true

  vars:
    keepalived_state: MASTER  # Default to MASTER, change as needed

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Install Keepalived
      package:
        name: keepalived
        state: present

    - name: Copy Keepalived configuration
      template:
        src: "keepalived_{{ keepalived_state | lower }}.conf.j2"
        dest: "/etc/keepalived/keepalived.conf"
      notify: restart keepalived  # Trigger the handler

  handlers:
    - name: restart keepalived
      service:
        name: keepalived
        state: restarted
